### ISSUE TITLE
a trouble with vllm.

### ISSUE THREAD

**Issue by auok1** [microsoft/ParrotServe#5]
After install，all versions meet the environmental requirements. But ,when I run "one-click scripts to run Parrot in a single machine with sample configs. ",an error occurred as shown in the figure.I tried for a long time but couldn't solve it.
<img width="456" alt="微信图片_20240718150234" src="https://github.com/user-attachments/assets/d48eaa6e-c8fb-4e5d-b658-e74c134c5f14">

**Comment by SiriusNEO** [comment]
Hi @auok1, thanks for your interest in our project.

From your screenshot, it seems that a DLL of CUDA can't be found. This is not a problem of Parrot, but a problem with your PyTorch+CUDA installation.

Could you first check whether PyTorch GPU can properly run on your machine (By creating two simple tensors on your GPU then add them) and whether vLLM can work (By running its examples)? Based on my experience, if you set the correct `LD_LIBRARY_PATH`, the problem can be solved.

**Comment by auok1** [comment]
> Hi @auok1, thanks for your interest in our project.
> 
> From your screenshot, it seems that a DLL of CUDA can't be found. This is not a problem of Parrot, but a problem with your PyTorch+CUDA installation.
> 
> Could you first check whether PyTorch GPU can properly run on your machine (By creating two simple tensors on your GPU then add them) and whether vLLM can work (By running its examples)? Based on my experience, if you set the correct `LD_LIBRARY_PATH`, the problem can be solved.
Thanks very much!😄

**Comment by SiriusNEO** [comment]
Close because there is no follow-up
